"""Initial migration

Revision ID: 1dcfa98579bb
Revises: 
Create Date: 2022-05-13 21:30:08.929244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcfa98579bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('f_name', sa.String(length=128), nullable=True),
    sa.Column('m_name', sa.String(length=128), nullable=True),
    sa.Column('l_name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.CHAR(length=11), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('nk_full_name', sa.String(length=128), nullable=True),
    sa.Column('nk_address', sa.String(length=128), nullable=True),
    sa.Column('nk_relation', sa.String(length=128), nullable=True),
    sa.Column('plate_number', sa.String(length=16), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_plate_number'), 'users', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_plate_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
