"""added active boolean for admins

Revision ID: f4607acee7ee
Revises: c1b6465d1661
Create Date: 2022-06-10 21:15:50.113640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4607acee7ee'
down_revision = 'c1b6465d1661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('is_confirmed')
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_active')
    # ### end Alembic commands ###
